### ISSUE TITLE
Support for Compose Web (Kotlin/Wasm)

### ISSUE THREAD

**Issue by nowiwr01w** [Lavmee/constraintlayout-compose-multiplatform#16]
Firstly, thank you for your work
Could you please share your thoughts about the support for Compose Web with Kotlin/Wasm? 
JetBrains has officially started supporting Kotlin/Wasm for Compose Multiplatform, but there seems to be no official support for Web (and any platform other than Android :c)

**Comment by Lavmee** [comment]
Hi, now the main blocker is WeakReference, so I need to find information about the possibility of using it on WASM.

**Comment by nowiwr01w** [comment]
@Lavmee can [this](https://github.com/qdsfdhvh/compose-imageloader/blob/d4f51ce2eb7276e3313e7ee28395392b28b69913/image-loader/src/wasmMain/kotlin/com/seiko/imageloader/util/Platform.wasm.kt) helps you?

**Comment by Lavmee** [comment]
You can try the new version 0.3.0-alpha01

**Comment by nowiwr01w** [comment]
```kotlin
commonMain.dependencies {
    /// ....
    implementation("tech.annexflow.compose:constraintlayout-compose-multiplatform:0.3.0-alpha01")
}
```
There is an error:
```
Could not resolve all dependencies for configuration ':composeApp:wasmJsCompileClasspath'.
> Could not find tech.annexflow.compose:constraintlayout-compose-multiplatform-wasm-js:0.3.0-alpha01.
```
I checked [mavenCentral](https://central.sonatype.com/namespace/tech.annexflow.compose) and it seems like you published only `js` version, but not `wasm-js`
@Lavmee

**Comment by Lavmee** [comment]
I'll check, but it seems wasm-js is present

https://central.sonatype.com/artifact/tech.annexflow.compose/constraintlayout-compose-multiplatform-wasm-js

**Comment by nowiwr01w** [comment]
Maybe mavenCentral had a bad time :D
It works, thank you for this great work <3

**Comment by GuilhE** [comment]
I guess for `beta01` is missing 🤔 
Could not resolve all dependencies for configuration ':shared-ui:wasmJsCompileClasspath'.
```
> Could not resolve all dependencies for configuration ':shared-ui:wasmJsCompileClasspath'.
   Could not find tech.annexflow.compose:constraintlayout-compose-multiplatform:0.3.0-beta01.
  Searched in the following locations:
    - https://dl.google.com/dl/android/maven2/tech/annexflow/compose/constraintlayout-compose-multiplatform/0.3.0-beta01/constraintlayout-compose-multiplatform-0.3.0-beta01.pom
    - https://repo.maven.apache.org/maven2/tech/annexflow/compose/constraintlayout-compose-multiplatform/0.3.0-beta01/constraintlayout-compose-multiplatform-0.3.0-beta01.pom
    - https://maven.pkg.jetbrains.space/public/p/compose/dev/tech/annexflow/compose/constraintlayout-compose-multiplatform/0.3.0-beta01/constraintlayout-compose-multiplatform-0.3.0-beta01.pom
    - https://androidx.dev/storage/compose-compiler/repository/tech/annexflow/compose/constraintlayout-compose-multiplatform/0.3.0-beta01/constraintlayout-compose-multiplatform-0.3.0-beta01.pom
  Required by:
      project :shared-ui
```
